apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: k8s-demo
  name: k8s-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-demo
    spec:
      containers:
      - image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        name: k8s-demo
        ports:
        - containerPort: 80
        env:
        - name: UNIQUE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
